### PR TITLE
remove OnlineUpdateService

### PR DESCRIPTION
**Pull request by MilanKral**
It's better to use app store update mechanism, either F-Droid or
Google Play.

Updating was done for debug version only.
The site https://atalk.mooo.com/ was not working.
https://atalk.sytes.net/releases/atalk-android/versionupdate.properties
was publishing old application version.

With this change the application would not need
android.permission.REQUEST_INSTALL_PACKAGES
anymore.

### CODE REVIEW

**Comment by cmeng-git** [comment]
All official releases for android playstore or Fdroid will always use the respective officiate site for update.

The online update is designed for use with debug version only; it was never intended for use with any official release update. From the source, it is clearly indicated that the online update service will only be started for BuildConfig.DEBUG version.
 
```
            else if (BuildConfig.DEBUG) {	
                // Perform software version update check on first launch - for debug version only	
                Intent dailyCheckupIntent = new Intent(getApplicationContext(), OnlineUpdateService.class);	
                dailyCheckupIntent.setAction(OnlineUpdateService.ACTION_AUTO_UPDATE_START);	
                startService(dailyCheckupIntent);	
            }
```

**Comment by MilanKral** [comment]
What is the use case for a separate update mechanism for debug builds?

It's not even working correctly as 
https://atalk.sytes.net/releases/atalk-android/versionupdate.properties
is pushing an old aTalk version (2.1.3).

The reason why I would like to remove REQUEST_INSTALL_PACKAGES permission is that 
REQUEST_INSTALL_PACKAGES could indicates a Potentially Harmful App to the user.

https://android-developers.googleblog.com/2017/08/making-it-safer-to-get-apps-on-android-o.html

**Comment by cmeng-git** [comment]
Both release and debug versions are signed with a different keys. They cannot be inter mixed. Install a debug version will require the user to uninstall the release version with all user data being purged, and vice versa. Also a normal user will never get to install a debug version from the official repository, nor he be prompt to download debug apk to install.

It is only used for users that would like to perform test using a debug version in case field problem can no be identified with debug info from a formal release. The debug version provides more debug info as compared to a formal release. As currently there is no debug user, therefore I did not bother to update the repository with the latest debug apk.

Even with the REQUEST_INSTALL_PACKAGES specified, there is no way for aTalk to install any apk without user permission. Android OS will always prompt user to give permission for any app that wants to install an apk from external source. Actually there are many app in official stores that permit user to install an external apk e.g. file explorer etc.

**Comment by MilanKral** [comment]
If there is no user of this functionality, then I recommend to remove the OnlineUpdateService. Or at least  comment out 

` 
           else if (BuildConfig.DEBUG) {	
                // Perform software version update check on first launch - for debug version only	
                Intent dailyCheckupIntent = new Intent(getApplicationContext(), OnlineUpdateService.class);	
                dailyCheckupIntent.setAction(OnlineUpdateService.ACTION_AUTO_UPDATE_START);	
                startService(dailyCheckupIntent);	
            }
`

and comment out REQUEST_INSTALL_PACKAGES

**Comment by cmeng-git** [comment]
I have moved all the online update source to debug build variant. So the official release does not contains the services.

**Pull request merged**
